import type { Quote } from '../types';

export const quotes: Quote[] = [
  { text: "People must give and then receive. First give and then you will have all. But instead, people want to first have all and then think of giving. This is not the right way.", author: "Meher Baba" },
  { text: "Nowadays even lust is taken for love. The subtle difference is missed. There is a very subtle difference between love and lust, but it is quite clear. They are two different things.", author: "Meher Baba" },
  { text: "As good is necessary, likewise bad is also necessary — just as positive and negative. Both are essential for action and evolution. If only good were to prevail everywhere, life would end!", author: "Meher Baba" },
  { text: "Everyone, no matter how depraved, can gradually become better and better until he becomes the best example for all mankind. There is always hope for everyone; none is utterly lost, and none need despair.", author: "Meher Baba" },
  { text: "The apparent is not real. Under many of life’s complicated problems are hidden some of the simplest truths which the veil of ignorance obscures from human vision.", author: "Meher Baba" },
  { text: "Devotees must always lean on Baba, not on each other. This does not mean you should not talk to one another, love one another... but you must not lean. You must love, serve and help one another and make each other love me more. Love, don’t lean.", author: "Meher Baba" },
  { text: "If you think I know everything, there is no need to express any want. If you think I know nothing, no amount of pleading for any ambition is of avail.", author: "Meher Baba" },
  { text: "The rain falls on both rocks and the soil. But the water flows away down the rock, while the earth soaks it up. Similarly, my mercy and grace are on all. But only those on the plain deserve it, while those who go about as if they are on top of a high mountain do not benefit by it!", author: "Meher Baba" },
  { text: "Long for what is real. You will then have no time for worrying over what may never happen.", author: "Meher Baba" },
  { text: "The unmistakable quality that masts possess is their ability to make one happy in their company; whereas in the company of a mad person one feels depression and sadness.", author: "Meher Baba" },
  { text: "Life is a series of experiences which need innumerable forms. Death is an interval in that one long life.", author: "Meher Baba" },
  { text: "Happiest is he who expects no happiness from others. Love delights and glorifies in giving, not receiving. So learn to love and give, and not to expect anything from others.", author: "Meher Baba" },
  { text: "You can keep only one Beloved in your hearts, although you can and may keep many in your mind. So, keep this one Beloved in your hearts and find me in every other heart!", author: "Meher Baba" },
  { text: "To take birth means to suffer. When suffering leads to real eternal happiness, we should not attach importance to this suffering. It is to eliminate suffering that suffering has to be. Great suffering means great liberation.", author: "Meher Baba" },
  { text: "Let not the dirt of the sanskaras of your thoughts and deeds touch you, by surrendering every thought and act at the feet of your Guru.", author: "Meher Baba" },
  { text: "Of the three most important things to be eliminated before attaining God-Realization—greed, lust, and backbiting—backbiting is the worst and most disastrous.", author: "Meher Baba" },
  { text: "Remember that the first step in spirituality is not to speak ill of others. All human beings have weaknesses and faults. Yet they are all God in their being.", author: "Meher Baba" },
  { text: "Those who die thinking of me come to me. They are liberated from the chain of birth and death and see me perpetually.", author: "Meher Baba" },
  { text: "If you cannot love, at least have the courage to give in.", author: "Meher Baba" },
  { text: "Mohammed’s greatness was not in Ka’aba but in Karbala, and this is my Karbala.", author: "Meher Baba" },
  { text: "Spirit communication is the experience of the semi-subtle by the physical senses in the conscious state. It is not a sign of advancement on the divine path.", author: "Meher Baba" },
  { text: "True knowledge is that knowledge which makes man after Self-Realization or union with God assert that his real Self is in everything and everybody.", author: "Meher Baba" },
  { text: "The heart of the Perfect One is at once soft like butter and hard like steel.", author: "Meher Baba" },
  { text: "The entire fabric of the universe serves but one purpose: the realization of God.", author: "Meher Baba" },
  { text: "There is no higher or lower goal. There is only one goal, Self-Realization.", author: "Meher Baba" },
  { text: "When man becomes God, a lineage is there, but when God becomes man there is no lineage. As for me, I have to come back again and again. There is pleasure in it and a kind of imprisonment, too.", author: "Meher Baba" },
  { text: "The objective of spiritual advancement is not so much ‘works’ but the quality of life free from ego-consciousness.", author: "Meher Baba" },
  { text: "The way to increase knowledge is to put into practice that bit of spiritual wisdom a person may already happen to have.", author: "Meher Baba" },
  { text: "Remember this much: the whole world is nothing but a zero, and everything connected with it is without sum and substance. Mind is the universe, Mind is the man, the woman, the beast.", author: "Meher Baba" },
  { text: "To gulp down anger is the most courageous act one can perform. One who does it becomes humble.", author: "Meher Baba" },
  { text: "When the Creator created creation, there were no temples, no mosques, no churches, no synagogues... When rituals came into existence, God gradually began to fade out of it.", author: "Meher Baba" },
  { text: "The Master is absolutely necessary for anyone to arrive at self-knowledge... he enables others to come into the full possession of their own latent possibilities.", author: "Meher Baba" },
  { text: "When nothing upsets you, you are at the beginning of the path. When you desire nothing, you are halfway on the path; when nothing becomes everything, you are perfected.", author: "Meher Baba" },
  { text: "Let love annihilate your lower self and reveal My Infinite Self.", author: "Meher Baba" },
  { text: "One of the most difficult things to learn is to render service without bossing, without making a fuss about it, and without any consciousness of high and low.", author: "Meher Baba" },
  { text: "If a person wants to take the pearl from the bottom of the ocean, then he should not shout at the pearl to come up while he sits on the beach. He should try his hardest to plunge to the bottom of the ocean to get it.", author: "Meher Baba" },
  { text: "Spiritual jealousy leads to advancement, while material jealousy leads to ruination and hatred.", author: "Meher Baba" },
  { text: "Only God is real, and everything else is a mere motion picture!", author: "Meher Baba" },
  { text: "I am eternally crucified. When the burden is especially heavy, I sometimes let my disciples share it, giving to each as much as they can bear.", author: "Meher Baba" },
  { text: "One cannot know Existence until one exists in that Existence.", author: "Meher Baba" },
  { text: "Neither seek death nor fear it, and when death comes to you it is converted into a stepping stone to the higher life.", author: "Meher Baba" },
  { text: "Worry eats everyone. Worry is the master of all. But those who swallow worry, they are the ones who become fakirs.", author: "Meher Baba" },
  { text: "My accident was no ‘accident,’ and it all comes to one thing; what I wanted has happened and what I want will happen.", author: "Meher Baba" },
  { text: "When love is not at its height, it always creates a mess.", author: "Meher Baba" },
  { text: "Time is the interval between your very first impression and your very last impression.", author: "Meher Baba" },
  { text: "I am Truth. No amount of voluminous praise will raise me higher, nor can any carping criticism pull me down. I am what I am and will ever be so.", author: "Meher Baba" },
  { text: "You make the effort and I will give you the victory. It is a divine struggle with purpose behind it. Do not fight against it.", author: "Meher Baba" },
  { text: "Reflection is from the Real, but reflection is not real.", author: "Meher Baba" },
  { text: "Go on digging until you find water. Don't keep changing the spot.", author: "Meher Baba" },
  { text: "All rivers flow in me. I am the ocean. Stop looking elsewhere, and look only at the ocean.", author: "Meher Baba" },
  { text: "Mercy is one thing and compassion is something else. I do not show mercy in the ordinary, worldly sense, but I do have compassion.", author: "Meher Baba" },
  { text: "Feelings and emotions are only the creation of mind and energy. Love is the creation of the soul.", author: "Meher Baba" },
  { text: "If a man is dissatisfied with his environment, it is usually because he does not know how to properly adjust himself to it. He should think, 'What is the lesson that I should learn from this experience?'", author: "Meher Baba" },
  { text: "Poverty, if cheerfully endured, develops humility and patience, and can greatly assist spiritual progress. It is a test of character.", author: "Meher Baba" },
  { text: "One must sincerely try to do his duties, but the results must always be left with God. Worrying about the results is no good and of no use.", author: "Meher Baba" },
  { text: "Working for and serving others, and undergoing so much strain, is very good. It wipes out past karmas.", author: "Meher Baba" },
  { text: "Cease the mental tension. Train your mind to pass over thoughts. Do not give countenance to them until such time that you can surrender the mind itself.", author: "Meher Baba" },
];
